package com.pro.hbm;
// Generated Aug 7, 2014 12:35:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CreditUserDetails generated by hbm2java
 */
public class CreditUserDetails  implements java.io.Serializable {


     private Integer id;
     private String firstname;
     private String lastname;
     private String payId;
     private String response;
     private Date createdAt;

    public CreditUserDetails() {
    }

    public CreditUserDetails(String firstname, String lastname, String payId, String response, Date createdAt) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.payId = payId;
       this.response = response;
       this.createdAt = createdAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPayId() {
        return this.payId;
    }
    
    public void setPayId(String payId) {
        this.payId = payId;
    }
    public String getResponse() {
        return this.response;
    }
    
    public void setResponse(String response) {
        this.response = response;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


